class Hotel {
  constructor(customersData, bookingsData, roomsData) {
    this.customer = customersData;
    this.rooms = roomsData;
    this.bookings = bookingsData;
  }
}

export default Hotel;

//WHAT WOULD GO HERE ?? WHAT TYPE OF DATA WOULD BE PASSED HERE?

  // WHAT PROPERTIES WOULD THIS HAVE ?
  // WOULD THIS INCLUDE ROOM AND BOOKING PROPERTIES ?
  // WOULD THIS TIE TO MY CUSTOMER CLASS ? 
  // WHAT METHODS DO I NEED TO THINK ABOUT ? 
  // WHAT WOULD THIS CLASS SERVE PURPOSE ? 
  
  // NOT SURE WHAT I NEED TO CREATE NOW. I HAVE ALL THE BOOKING,ROOM, AND CUSTOMER CLASS NOW
  // HOW WOULD ALL THESE CLASS TIE ? 

  // KINDA CONFUSED WHATS THE PURPOSE TO USE CLASSES.